# Алгоритм решения

## Постановка задачи
Пусть дана система $$Ax = b.\quad (1)$$
    
Предполагаем, что задача является корректно поставленной. Нам необходимо:
1. найти решение системы указанным методом;
2. вычислить вектор невязки;
3. вычислить определитель матрицы системы;
4. найти матрицу, обратную к матрице системы;
5. найти число обусловленности матрицы системы.

## Метод вращений

$\bullet$ _**Матрицей вращения** называется матрица вида_ $$T_{ij}  = \bordermatrix{
			& & & i & &j & & \cr
			& 1 & \dots & 0 & \dots & 0 & \dots & 0 \cr
			& \vdots & \ddots & \vdots & \vdots & \vdots & \ddots & \vdots \cr
			i& 0 & \dots & \cos\varphi & \dots & -\sin\varphi & \dots & 0 \cr
			& \vdots & \ddots & \vdots & \ddots & \vdots & \ddots & \vdots \cr
			j & 0 & \dots & \sin\varphi & \dots & \cos\varphi & \dots & 0 \cr
			& \vdots & \ddots & \vdots & \vdots & \vdots & \ddots & \vdots \cr
			& 0 & \dots & 0 & \dots & 0 & \dots & 1 \cr}. \quad(2)$$
Если мы умножим матрицу $A$ на матрицу $T_{ij}$ слева, то мы получим матрицу $B = T_{ij}A$, у которой элементы $i$-ой и $j$-ой строк будут изменены $$\begin{cases}
	b_{ik} = a_{ik}\cos \varphi - a_{jk}\sin\varphi,\\
	b_{jk} = a_{ik}\sin\varphi + a_jk\cos\varphi,
	\end{cases}\quad k = \overline{1,n},\quad(3)$$
а остальные элементы не изменятся.

Запишем формулы, обеспечивающие выбор $\varphi$. Предположим, что нам нужно исключить $x_s$ неизвестную из $j$-ого уравнения, то есть коэффициент при этом значении должен быть равен нулю. Для этого нам необходимо в формуле (3) положить $k=s$ и приравнять этот элемент к нулю. То есть $$a_{is}\sin \varphi + a_{js}\cos\varphi = 0.$$
Получили уравнение с одной неизвестной. Очевидно $$\operatorname{tg}\varphi = -\dfrac{a_{js}}{a_{is}},\ a_{is} \ne 0.$$
	Отсюда $$\begin{cases}
		\cos \varphi = \dfrac{a_{is}}{\sqrt{a_{is}^2 + a_{js}^2}},\\
		\sin\varphi = - \dfrac{a_{js}}{\sqrt{a_{is}^2 + a_{js}^2}}.
	\end{cases}\quad(4)$$
Заметим, что в формуле (4) $a_{is}$ может быть равным нулю. Но если $a_{js} = 0$, то $T_{ij} = E$.

## Алгоритм метода
**Первый этап.**
Последовательно будем умножать исходную систему на матрицы $$T_1 = T_{12}, T_{13},\ldots, T_{1n}.$$
	 При этом первая строка получится такая, какая получится, а все остальные строки будут без переменной $x_1$. Итак у нас будет количество умножений $n-1$ и для каждого $k$-ого умножения запишем формулу $$\cos\varphi_{1,k} = \dfrac{a_{11}^{1,k-1}}{\sqrt{(a_{11}^{1,k-1})^2 + (a_{k1}^{1,k-1})^2}},\quad \sin\varphi_{1,k} =- \dfrac{a_{k1}^{1,k-1}}{\sqrt{(a_{11}^{1,k-1})^2 + (a_{k1}^{1,k-1})^2}}, \quad k =\overline{2,n}\quad (5)$$
 Для пересчета ненулевых элементов запишем формулу
 $$\begin{cases}
 	a_{1j}^{1,k} = a_{1j}^{1,k-1}\cos\varphi_{1,k} -a_{kj}^{1,k-1}\sin\varphi_{1,k},\quad j=\overline{1,n},\ k=\overline{2,n},\\
 	a_{kj}^{1,k} = a_{1j}^{1,k-1}\sin\varphi_{1,k} +a_{kj}^{1,k-1}\cos\varphi_{1,k},\quad j=\overline{1,n},\ k=\overline{2,n},\\
 	a_{ij}^{1,k} = a_{ij}^{1,k-1},\quad i\ne 1,\ i \ne k.
 \end{cases}\quad(6)$$
 $$\begin{cases}
 	b_1^{1,k} = b_1^{1,k-1}\cos\varphi_{1,k} - b_k^{1,k-1}\sin\varphi_{1,k},\\
 	b_k^{1,k} = b_1^{1,k-1}\sin\varphi_{1,k} + b_k^{1,k-1}\cos\varphi_{1,k},\\
 	b_p^{1,k} = b^{1,k-1}_p,\quad p\ne 1, p\ne k
 \end{cases} \quad(7)$$
Данная формула соответствует первому этапу.

По окончанию первого этапа мы получаем систему $$A^1x = b^1,\quad A^1 = T_{1n}\ldots T_{13}T_{12}A = T_1A, b^1 = T_1b.$$

Все элементы ниже главной диагонали в полученной матрице будут равны нулю.

**Второй этап.** 

Далее во втором этапе нам нужно домножить на матрицу $$T_2 = T_{2n}\ldots T_{23}.$$ И так далее.

**n-1 этап.** 

Получим систему $$A^{n-1}x = b^{n-1},\quad A^{n-1} = T_{n-1}T_{n-2}\ldots T_1A, b^{n-1} =  T_{n-1}T_{n-2}\ldots T_1b,$$ матрица которой является верхней треугольной. Для того, чтобы завершить этот метод необходимо осуществить обратный ход метода Гаусса.

## Обратный ход

Обратный ход состоит в последовательном нахождении неизвестных $$x_i = \dfrac{q_i - \sum_{j=i+1}^{n}c_{ij}x_j}{a_{ii}},\ i=\overline{n-1, 1}.$$
	$$x_n = \dfrac{q_n}{a_{nn}}.$$

Метод вращения является более трудоемким, чем метод отражения. Количество операций этого метода $Q(n)  = O(n^3)$, но количество умножений будет в 2 раза больше, чем у метода вращений.

## Вычисление вектора невязки

После применения обратного хода мы получаем вектор решений $x^*$. Вектор невязки определяется формулой $$r = Ax^* - b,$$ где $A$ и $b$ - матрица и вектор исходной системы.

## Вычисление определителя

$$|A| = a^{n-1}_{11}\cdot a^{n-1}_{22}\cdot\ldots\cdot a^{n-1}_{nn}.$$

## Вычисление обратной матрицы

Для вычисления обратной матрицы рассмотренным алгоритмом будем решать систему $$AX = E,$$ где столбец $X$ и будет содержать искомую обратную матрицу.

## Вычисление числа обусловленности

Для вычисления числа обусловленности воспользуемся формулой, определяющей его, $$\nu(A) = | | A| | \cdot | | A^{-1} | |.$$
При решении будет вычислять его, используя сферическую норму матрицы.

# Листинг программы

In [4]:
import numpy as np
import math

## Функция алгоритма

In [64]:
def rotation_method(A, b):
    E = np.eye(A.shape[0]) # Единичная матрица
    for k in range(A.shape[0] - 1): # Цикл шагов алгоритма
        T_k = np.eye(A.shape[0]) # Инициализируем матрицу T_k, на которую мы умножаем матрицу A на k-ом шаге
        for j in range(k + 1, A.shape[0]): # Цикл для подсчета n-k матриц T_kj, из произведения которых саму матрицу T_k
            cos_phi = A[k][k] / np.sqrt(A[k][k]**2 + A[j][k]**2) # Считаем косинус по формуле (4)
            sin_phi = - A[j][k] / np.sqrt(A[k][k]**2 + A[j][k]**2) # Считаем синус по формуле (4)
            T = E.copy() # Инициализируем матрицу T_kj, в k-ой и j-ой строках которой будут стоять рассчитанные синусы и косинусы...
            # ...в соответствии с формулой (2)
            
            # Расставляем на нужные позиции синус и косинус как в формуле (2)
            T[k][k] = cos_phi
            T[k][j] = -sin_phi
            T[j][k] = sin_phi
            T[j][j] = cos_phi
            
            # Домножаем матрицу T_k на T_kj слева
            T_k = np.dot(T, T_k)
        # Домножаем матрицу A и столбец на матрицу вращений T_k (последняя формула в первом этапе)
        A = np.dot(T_k, A) # A^k = T_kA^(k-1)
        b = np.dot(T_k, b) # b^k = T_kb^(k-1)
        
    # Вычисление определителя
    det = 1
    for k in range(A.shape[0]):
        det *= A[k][k] # Произведение всех диагональных элементов получившейся треуголньой матрицы
    
    if len(b.shape) == 1:    # Если мы решаем систему Ax = b
        x = np.zeros(A.shape[0]) # Заводим нулевой вектор для будущего решения системы
        # Обратный ход метода Гаусса
        for i in range(A.shape[0]-1, -1, -1):
            summary = 0
            for j in range(i+1, A.shape[0]):
                summary += A[i][j]*x[j]
            x[i] = (b[i] - summary) / A[i][i]
        
        #Вычисление вектора невязки
        r = np.zeros(A.shape[0]) # Переменная для хранения значения вектора невязки
        for i in range(A.shape[0]):
            for j in range(A.shape[0]):
                r[i] += A[i][j]*x[j]; # r+=Ax
            r[i] -= b[i] #r-=b
        
        return x, r, det # Возвращаем значения решения, вектора невязки и определителя матрицы
    
    else: # Если решаем систему AX=E
        x = np.zeros((A.shape[0], A.shape[0])) # Заводим нулевую матрицу для хранения будущей обратной матрицы
        # Обратный ход метода Гаусса
        for i in range(A.shape[0]-1, -1, -1):
            summary = 0
            for j in range(i+1, A.shape[0]):
                summary += A[i][j]*x[i][j]
            for j in range(A.shape[0]):
                x[i][j] = (b[i][j] - summary) / A[i][i]
        
        return x # Возвращаем значение обратной матрицы

# Проверка результатов

1. При заданном $n$ сгенерировать случайным образом квадратную матрицу размера $n\times n$, имеющую диагональное доминирование. Элементы матрицы - действительные числа с двумя знаками после запятой.

In [65]:
from random import randint
 
n = int(input())
 
A = np.array([[randint(10, 1000) / 100 for _ in range(n)] for _ in range(n)]).astype(float)

summary = 0
for i in range(n):
    for j in range(n):
        if i != j:
            summary += math.fabs(A[i][j])
for i in range (n):
    if A[i][i] <= summary:
        A[i][i] = randint(int(summary)*100, 10000) / 100

print(*A, sep='\n')

 5


[95.76  1.68  6.41  7.04  5.48]
[ 1.55 98.83  9.98  1.26  0.2 ]
[ 2.73  7.97 94.65  4.07  8.74]
[ 2.18  0.73  7.27 96.32  5.44]
[ 9.09  1.87  8.35  2.12 97.67]


2. Сгенерировать случайным образом вектор решений $x$ (два знака после запятой).

In [66]:
x = np.array([randint(10, 1000) / 100 for _ in range(n)]).astype(float)

print(*x, sep='\n')

2.79
7.06
5.03
4.61
5.2


3. По сгенерированным данным вычислить вектор $b$ свободных членов системы по формуле $b = Ax$.

In [67]:
b = A.dot(x)

print(*b, sep='\n')

372.2239
759.1122999999999
604.1851
520.1273
598.221


4. Для полученных данных:

    a) найти решение системы указанным методом.

In [68]:
_x, r, det = rotation_method(A, b)

print(*_x, sep='\n')

2.7902378358701774
7.059996605323458
5.030221157321145
4.609892861292224
5.19839835189939


Выполнить проверку путем вычисления вектора невязки.

In [69]:
print(*r)

0.0 -0.00041181421318015055 -0.006474086842672477 -0.01826979519012184 -0.15324208478750734


б) найти матрицу, обратную к матрице системы.

In [70]:
A_inv = rotation_method(A, np.eye(n))
print(*A_inv, sep='\n')

[0.01033313 0.00016726 0.00029462 0.00023536 0.00098165]
[-2.01831591e-04  1.00538217e-02  8.00631792e-04  6.60238868e-05
  1.55426141e-04]
[-0.00038167 -0.00086553  0.01055053  0.00078584  0.00081007]
[-2.18623195e-04 -1.06830727e-05 -7.88682070e-04  1.04306473e-02
  3.89426430e-05]
[-0.0009572  -0.00011259 -0.00083129 -0.00012176  0.01037366]


Выполнить проверку;

In [71]:
E = np.dot(A_inv, A)

for i in range(n):
    for j in range(n):
        E[i,j] = round(np.absolute(E[i,j]), 0) # Преобразуем "единичниую" матрицу, округлив до двух знаков после запятой
        
print(*E, sep='\n')

[1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 0. 1.]


в) вычислить определитель матрицы системы;

In [72]:
print(det)

8190409292.88198


г) найти число обусловленности.

In [73]:
nu = np.linalg.norm(A) * np.linalg.norm(A_inv)
print(nu)

5.065563118886005
