In [36]:
import numpy as np
import math

A = np.array([
    [6.25, -1, 0.5],
	[-1, 5, 2.12],
	[0.5, 2.12, 3.6]])
B = np.array([[7.5], [-8.68], [-0.24]])

C = np.eye(A.shape[0]) - (np.dot(A.T, A)) / max(np.linalg.eigvals(np.dot(A.T, A)))

print(*C, sep='\n')

[ 0.17960243  0.20737615 -0.05708441]
[ 0.20737615  0.37941007 -0.360863  ]
[-0.05708441 -0.360863    0.63969869]


In [37]:
D = (np.dot(A.T, B) / max(np.linalg.eigvals(np.dot(A.T, A))))
print(*D, sep='\n')

[1.12815477]
[-1.04621778]
[-0.31575716]


In [38]:
print(*abs(np.linalg.eigvals(C)))

0.9309731403755809 9.628392918029083e-17 0.2677380489149452


In [57]:
def F(X_n):
    return np.dot(C, X_n) + D
    
def aposteriori(X_n, X_n1, alpha):
    return alpha / (1 - alpha) * np.linalg.norm(X_n - X_n1, 2)

def apriori(X_0, X_1, epsilon, alpha):
    return math.floor(math.log(epsilon * (1 - alpha) / (np.linalg.norm(X_0 - X_1, 2)), alpha)) + 1

def msa(X_0, X_1, alpha, epsilon):
    iterations = 0
    while True:
        iterations += 1
        X_0 = X_1
        X_1 = F(X_0)
        if aposteriori(X_1, X_0, alpha) <= epsilon:
            break
    return X_1, iterations

X_0 = np.zeros([3,1])
alpha = np.linalg.norm(C, 2)
epsilon = 1e-4

print('compression coefficient: ' + str(alpha))

n_apr = apriori(X_0, F(X_0), epsilon, alpha)
print('apriori number of iterations: ' + str(n_apr))

last_iteration, iterations = msa(X_0, F(X_0), alpha, epsilon)
print('aposteriori number of iterations: ' + str(iterations))
print('solution: \n' + str(last_iteration))

compression coefficient: 0.9309731403755804
apriori number of iterations: 173
aposteriori number of iterations: 136
solution: 
[[ 0.80002193]
 [-1.99994162]
 [ 0.99992337]]


In [40]:
def matrix_norm(matrix):
    columns = []
    rows = []
    for i in range(matrix.shape[0]):
        row_abs = [abs(matrix[i][j]) for j in range(matrix.shape[0])]
        columns.append(sum(row_abs))
    
    for j in range(matrix.shape[0]):
        col_abs = [abs(matrix[i][j]) for i in range(matrix.shape[0])]
        rows.append(sum(col_abs))

    return max(columns), max(rows)

In [55]:
matrix_norm(C)

(1.0758760630087343, 1.0758760630087343)

In [8]:
np.linalg.norm(C, 2)

0.9309731403755804

In [21]:
np.sqrt(max(np.linalg.eigvals(C)))

0.9648694939604946

In [56]:
A @ last_iteration

array([[ 7.5000404 ],
       [-8.67989248],
       [-0.24014113]])