# Алгоритм решения

## Постановка задачи
Пусть дана система $$Ax = b.\quad (1)$$
    
Предполагаем, что задача является корректно поставленной. Нам необходимо:
1. найти решение системы указанным методом;
2. вычислить вектор невязки;
3. вычислить определитель матрицы системы;
4. найти матрицу, обратную к матрице системы;
5. найти число обусловленности матрицы системы.

## Выбор главного элемента по строке.

На каждом $k$-ом шаге прямого хода в качестве ведущего выбирается максимальный по модулю элемент в неприведенной части строки. После этого столбец расширенной матрицы соотвествующий главному элементу переставляется с $k$-ым столбцом и производится перенумерация коэффициентов при неизвестных. Для этого заводим массив индексов, в котором будем производить перестановки.

Запишем систему в координатном виде:
	$$\begin{cases}
		a_{11}x_1 + a_{12}x_2 + \ldots + a_{1n}x_n = b_1,\\
		a_{21}x_1 + a_{22}x_2 + \ldots + a_{2n}x_n = b_2,\\
		\vdots\\
		a_{n1}x_1 + a_{n2}x_2 + \ldots + a_{nn}x_n = b_n.
	\end{cases}\quad (1)$$
    
Предположим, что $a_{11}\ne0$. Разделим первое уравнение системы (1) на $a_{11}$ и получим:
$$x_1 + c_{11}x_2 + \ldots + c_{1n}x_n = q_1 \quad (2),$$ где $c_{1j} = \dfrac{a_{1j}}{a_{11}}$, $j = \overline{2,n}$, $q_1=\dfrac{b_1}{a_{11}}$.
С помощью уравнения $(2)$ исключим $x_1$ из всех остальных уравнений, начиная со 2-го. Таким образом, первое уравнение не поменяется, а все остальные примут вид 
    $$\begin{cases}
		a_{22}^1x_2 +a_{23}^1x_3+ \ldots + a_{2n}^1x_n = b_2^1,\\
		\vdots\\
		a_{n2}^1x_2 + a_{n3}^1x_3 + \ldots + a_{nn}^1x_n = b_n^1,
	\end{cases}\quad(3)$$
    
где $a_{ij}^1 = a_{ij} - c_{1j}a_{i1}$, $b_i^1 = b_i - q_1a_{i1}$, $i,j = \overline{2,n}$.
Мы завершили первый шаг прямого хода.

$\bullet$ Элемент $a_{11}$ называется **ведущим** элементом шага.

Далее считаем, что $a_{22}$ ведущий элемент. Аналогично делим на него и исключаем $x_2$ и так далее до $x_{nn}$. Окончательно приходим к системе с верхней треугольной матрицей следующего вида 
$$\begin{cases}
	x_1 + c_{12}x_2 + \ldots + c_{1n} = q_1,\\
	x_2 + \ldots + c_{2n} = q_2,\\
	\vdots\\
	x_n = q_n.
	\end{cases}\quad (4)$$

## Прямой ход.

Для того, чтобы получить общие формулы вычисления матрицы, введем следующие обозначения:
1. $a_{kj}^0 = a_{kj}, k,j=\overline{1,n}$ - исходные элементы матрицы;
2. $b_k^0 = b_k$, $k = \overline{1,n}$ - компоненты вектора правых частей исходной матрицы.
	
Тогда 
    $$c_{kj} = \dfrac{a_{kj}^{k-1}}{a_{kk}^{k-1}},\ j=\overline{k+1,n},\ k = \overline{1,n-1},$$
	$$a_{ij}^k = a_{ij}^{k-1} - a_{ik}^{k-1}c_{kj},\ i,j=\overline{k+1,n},\ k = \overline{1,n-1},$$
	$$q_k = \dfrac{b_k^{k-1}}{a_{kk}^{k-1}},\ k=\overline{1,n},$$
	$$b_i^k = b_i^{k-1} - a_{ik}^{k-1}q_k,\ i=\overline{k+1,n},\ k = \overline{1,n-1}.$$
	
Метод Гаусса завершен, числа $a_{kk}^{k-1}$, $k=\overline{1,n}$ - ведущие элементы.

## Обратный ход

Обратный ход состоит в последовательном нахождении неизвестных $$x_i = \dfrac{q_i - \sum_{j=i+1}^{n}c_{ij}x_j}{a_{ii}},\ i=\overline{n-1, 1}.$$
	$$x_n = \dfrac{q_n}{a_{nn}}.$$

## Вычисление вектора невязки

После применения обратного хода мы получаем вектор решений $x^*$. Вектор невязки определяется формулой $$r = Ax^* - b,$$ где $A$ и $b$ - матрица и вектор исходной системы.

## Вычисление определителя

$$|A| = (-1)^m\cdot a^0_{11}\cdot a^1_{22}\cdot\ldots\cdot a^{n-1}_{nn},$$
	где $m$ - количество перестановок, осуществленных при прямом ходе метода Гаусса.

## Вычисление обратной матрицы

Задача нахождения матрицы обратной матрице $A$ эквивалентна задаче решения матричного уравнения $$AX = E,$$ где $X = A^{-1}$ - искомая матрица. Если обозначить $x^{(1)}, \ldots, x^{(n)}$ - столбцы матрицы $X$, то эта матрица может быть найдена по столбцам решения системы вида $$Ax^{(j)} = \delta^{(j)},\ \delta^{(j)} = (\delta_{1j}, \ldots, \delta_{nj})^T,\ x^{(j)} = (x_{1j},\ldots, x_{nj})^T.\ j=\overline{1,n}\qquad(1)$$
	Решение всех $n$ систем доставит нам все столбцы обратной матрицы. Таким образом, задача нахождения обратной матрицы сводится к применению метода Гаусса $n$ раз к системе вида $(1)$.

## Вычисление числа обусловленности

Для вычисления числа обусловленности воспользуемся формулой, определяющей его, $$\nu(A) = | | A| | \cdot | | A^{-1} | |.$$
При решении будет вычислять его, используя сферическую норму матрицы.

# Листинг программы

In [1]:
import numpy as np
import math

## Функция алгоритма

In [2]:
def gaussian(matrix_, inhomogeneity):
    matrix = matrix_.copy() # Копируем исходную матрицу в локальную переменную
    insertions = 0 # Число перестановок
    indexes = [i for i in range (matrix.shape[0])] # Вектор индексов
    unit_matrix = np.eye(matrix.shape[0]) # Единичная матрица
    
    # Выбор главного элемента по строке
    for k in range(matrix.shape[0]):
        leading_column = k # Столбец, в котором ведущий элемент, считаем равным номеру шага
        for i in range(k, matrix.shape[0]): # находим максимальный по модулю элемент в строке
            if math.fabs(matrix[k][i]) > math.fabs(matrix[leading_column][k]): # Если нашли в строке элемент ...
                # ...больший, чем ведущий, то..
                leading_column = i # Номер столбца с ведущим элементом принимает значение того, ...
                # ...в котором находится больший элемент, чем текущий ведущий элемент
        for j in range(k, matrix.shape[1]): # меняем местами столбец, в котором главный элемент, со столбцом равном номеру шага
            matrix[j][leading_column], matrix[j][k] =  matrix[j][k], matrix[j][leading_column]
        insertions+=1 # повышаем число перестановок
        indexes[leading_column], indexes[k] = indexes[k], indexes[leading_column]
        
        # Прямой ход (полностью дублирует формулу прямого хода, указанную выше)
        q = inhomogeneity[k] / matrix[k][k] 
        for j in range(matrix.shape[0] - 1, k - 1, -1):
            c = matrix[k][j] / matrix[k][k]
            for i in range(matrix.shape[0] - 1, k, -1):
                matrix[i][j] = matrix[i][j] - matrix[i][k]*c
                if j == matrix.shape[0] - 1:
                    inhomogeneity[i] = inhomogeneity[i] - matrix[i][k]*q
                
    
    # Обратный ход (полностью дублирует формулу обратного хода, указанную выше)
    results_with_insertions = np.zeros(matrix.shape[0]) # Нулевой вектор
    for i in range(matrix.shape[0]-1, -1, -1):
        summary = 0
        for j in range(i+1, matrix.shape[0]):
            summary += matrix[i][j]*results_with_insertions[j]
        results_with_insertions[i] = (inhomogeneity[i] - summary) / matrix[i][i]
        
    
    # Перенумерация индексов в векторе решений
    results = np.zeros(matrix.shape[0]) # Создаем итоговый вектор решений, заполненный нулями
    for i in range(matrix.shape[0]):
        results[indexes[i]] = results_with_insertions[i] # Переносим значения из получившегося столбца решений ...
        # в созданный в той последовательности, в которой элементы столбца должны расоплагаться
        
    #Вычисление вектора невязки
    discrepancy_vector = np.zeros(matrix.shape[0]) # Создаем вектор заполненный нулями
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[0]):
            discrepancy_vector[i] += matrix[i][j]*results[j]; # r += Ax
        discrepancy_vector[i] -= inhomogeneity[i] # r -= b
    
    # Вычисление определителя
    determinant = (-1)**insertions # Создаем переменную, в которой содержится (-1) в степени числа перестановок
    for k in range(matrix.shape[0]):
        determinant *= matrix[k][k] # Перемножаем все диагональные элементы получившейся треугольной матрицы
        
    return results, discrepancy_vector, determinant; # Возвращаем значения решения, невязки и определителя

## Проверка результатов

1. При заданном $n$ сгенерировать случайным образом квадратную матрицу размера $n\times n$, имеющую диагональное доминирование. Элементы матрицы - действительные числа с двумя знаками после запятой.

In [14]:
from random import randint
 
n = int(input())
 
A = np.array([[randint(10, 1000) / 100 for _ in range(n)] for _ in range(n)]).astype(float)

summary = 0
for i in range(n):
    for j in range(n):
        if i != j:
            summary += math.fabs(A[i][j])
for i in range (n):
    if A[i][i] <= summary:
        A[i][i] = randint(int(summary)*100, 10000) / 100

print(*A, sep='\n')

 4


[67.37  4.64  2.42  1.47]
[ 9.05 75.03  5.27  6.29]
[ 2.01  5.65 88.83  0.65]
[ 4.68  4.57  3.27 57.79]


2. Сгенерировать случайным образом вектор решений $x$ (два знака после запятой).

In [15]:
x = np.array([randint(10, 1000) / 100 for _ in range(n)]).astype(float)

print(*x, sep='\n')

7.61
3.22
4.36
0.64


3. По сгенерированным данным вычислить вектор $b$ свободных членов системы по формуле $b = Ax$.

In [16]:
b = A.dot(x)

print(*b, sep='\n')

539.1185000000002
337.46990000000005
421.20390000000003
101.57300000000001


4. Для полученных данных:

    a) найти решение системы указанным методом.

In [17]:
_x, r, det = gaussian(A, b)

print(*_x, sep='\n')

7.610000000000001
3.2200000000000006
4.359999999999999
0.64


Выполнить проверку путем вычисления вектора невязки.

In [18]:
print(*r, sep='\n')

-1.1368683772161603e-13
0.0
0.0
0.0


б) найти матрицу, обратную к матрице системы.

In [8]:
E = np.eye(n)
A_inv = []
for i in range(n):
    A_inv.append(gaussian(A, E[i])[0])
print(*A_inv, sep='\n')

[ 1.23606647e-02 -1.02530450e-03 -1.12416097e-03  7.35057736e-05]
[-0.00025908  0.01132105 -0.00089068 -0.00071391]
[-0.00078568 -0.00055531  0.01066571 -0.00097246]
[-1.19258651e-03 -8.21598119e-04  8.37274400e-05  1.00704261e-02]


Выполнить проверку;

In [9]:
E = np.dot(A_inv, A)

for i in range(n):
    for j in range(n):
        E[i,j] = round(np.absolute(E[i,j]), 0) # Преобразуем "единичниую" матрицу, округлив до нуля знаков после запятой
        
print(*E, sep='\n')

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


в) вычислить определитель матрицы системы;

In [10]:
print(det)

67835141.89020617


г) найти число обусловленности.

In [11]:
nu = np.linalg.norm(A, 2) * np.linalg.norm(A_inv, 2)
print(nu)

1.4507429722667433
