# Алгоритм решения

## Постановка задачи
Пусть дана система $$Ax = b.\quad (1)$$
    
Предполагаем, что задача является корректно поставленной. Нам необходимо:
1. найти решение системы указанным методом;
2. вычислить вектор невязки;
3. вычислить определитель матрицы системы;
4. найти матрицу, обратную к матрице системы;
5. найти число обусловленности матрицы системы.

## Метод отражений 
$\bullet$ *Матрицей **отражения (Хаусхолдера)** называют матрицу вида $$V = E-2 \omega \omega^T,\quad(2)$$ где $\omega$ - вектор-столбец единичной длины в сферической норме, то есть $(\omega,\omega) = \omega^T\omega = 1$.*


Можно показать, что $\forall$ вектора $s \ne 0$ и заданного вектора $e$ единичной длины имеет место равенство $$Vs =\alpha e,\quad(3)$$ где $V$ - матрица отражений (2), в которой $$\omega = \kappa(s-\alpha e),\quad \kappa = \dfrac{1}{\sqrt[]{2(s, s-\alpha e)}},\ \alpha = \sqrt[]{(s,s)}.\quad(4)$$

Алгоритм метода отражения рассмотрим поэтапно, а затем запишем общую формулу.

## Первый этап. 
Используя формулу (4), образуем матрицу отражения $V^1$ по векторам $$s^1 = (a_{11}, a_{21}, \ldots, a_{n1})^T,\ e^1 = (1,0,\ldots, 0)^T.$$

Умножим слева исходную систему (1) на матрицу $V^1$. После умножения у нас получится система $$A^1 x = b^1,\quad A^1 = V^1 A,\ b^1 = V^1 b.$$

Легко видеть, что в матрице $A^1$ все элементы, стоящие ниже элемента $a_{11}$ стоит 0. Запишем формулы, отражающие, что произойдет с элементами матрицы $A$:
	$$\begin{cases}
		a_{11}^1 = \alpha_1,\\
		a_{ij}^1 = a_{ij}-2(g_j, \omega^1)\omega_i^1,\ i = \overline{1,n},\ j=\overline{2,n},\\
		b_{i}^1 = b_i -2(b, \omega^1)\omega_i^1,\ i=\overline{1,n},
	\end{cases}\quad(5)$$
    
где $$g_j = (a_{1j}, a_{2j},\ldots, a_{nj})^T.$$

Скалярное произведение определим как $$(g_j, \omega^1) - \sum_{p=1}^{n}g_{pj}w^1_p.$$

## Второй этап.
Строим матрицу $V^2$ по векторам $$s^1 = (0, a^1_{22}, \ldots, a^1_{n2})^T,\ e^2 = (0,1,\ldots, 0)^T.$$
	
Тогда мы образуем систему $$A^2 x = b^2,\quad A^2 = V^2 A^1,\ b^2 = V^2 b^1.$$

Легко увидеть, что в $A^2$ первая строка будет совпадать с $A^1$, а остальные элементы будут изменены по предыдущему алгоритму.

## Алгоритм. 
На любом $k$-ом шаге, $1\leq k \leq n-1$ мы строим векторы $$s^k = (0,\ldots, 0, a_{kk}^k-1,\ldots, a_{nk}^{k-1})^T,\quad e^k=(0,\ldots, 0,1,0,\ldots, 0)^T$$ образуем матрицу $V^k$ и преобразуем систему к виду $$A^k x = b^k.\quad(6)$$
Запишем, как меняются коэффициенты от шага в шагу: $$\begin{cases}
	a_{ij}^k = a_{ij}^{k-1},\quad i = \overline{1, k-1},\ j = \overline{1,n},\\
	a^k_{kk} = \alpha_k, \\
	a^k_{ij} = a_{ij}^{k-1} - 2(g_j^{k-1}, \omega^k)\omega_i^k,\quad i = \overline{k,n},\ j=\overline{k+1,n},\\
	b_i^k = b_i^{k-1},\quad i = \overline{1,k-1},\\
	b_i^k = b_i^{k-1} - 2(b^{k-1},\omega^k)\omega_i^k,\quad i = \overline{k,n}.
	\end{cases}\quad(7)$$
	В формуле (7) $$g_j^{k-1} = (a_{1j}^{k-1},\ldots, a_{nj}^{k-1}),$$
	$$(g_j^{k-1}, \omega^k) = \sum_{p=k}^{n} g_{pj}^{k-1} \omega_p^k,$$
	$$(b^{k-1}, \omega^k) = \sum_{p=k}^{n} b_p^{k-1} \omega_p^k.$$
После выполнения всех $n-1$ этапа мы получим матрицу $$A^{n-1}x = b^{n-1},$$ причем матрица $A^{n-1}$ является верхней треугольной. Далее после приведения к такому виду, чтобы записать решение, нам нужно записать формулы аналогичные обратному ходу метода Гаусса.

## Обратный ход

Обратный ход состоит в последовательном нахождении неизвестных $$x_i = \dfrac{q_i - \sum_{j=i+1}^{n}c_{ij}x_j}{a_{ii}},\ i=\overline{n-1, 1}.$$
	$$x_n = \dfrac{q_n}{a_{nn}}.$$

Число операций будет равно $Q(n) = O(n^3)$. В отличие от метода Гаусса количество умножений здесь будет в 2 раза больше. Однако, в отличие от метода Гаусса, число обусловленности мы не изменяем.

## Вычисление вектора невязки

После применения обратного хода мы получаем вектор решений $x^*$. Вектор невязки определяется формулой $$r = Ax^* - b,$$ где $A$ и $b$ - матрица и вектор исходной системы.

## Вычисление определителя

$$|A| = a^{n-1}_{11}\cdot a^{n-1}_{22}\cdot\ldots\cdot a^{n-1}_{nn}.$$

## Вычисление обратной матрицы

Для вычисления обратной матрицы рассмотренным алгоритмом будем решать систему $$AX = E,$$ где столбец $X$ и будет содержать искомую обратную матрицу.

## Вычисление числа обусловленности

Для вычисления числа обусловленности воспользуемся формулой, определяющей его, $$\nu(A) = | | A| | \cdot | | A^{-1} | |.$$
При решении будет вычислять его, используя сферическую норму матрицы.

# Листинг программы

In [1]:
import numpy as np
import math

## Функция алгоритма

In [2]:
def reflection_method(A, b):
    E = np.eye(A.shape[0]) # Единичная матрица
    for k in range(A.shape[0] - 1): # Цикл шагов алгоритма
        s = np.zeros(A.shape[0]) # Создаем нулевой вектор s
        for i in range(k, A.shape[0]):
            s[i] = A[i][k] # Вектор s на k-ом шаге принимает значение k-ого столбца исходной матрицы системы
        e = np.array([E[i][k] for i in range(A.shape[0])]) # Вектор e равен k-ому столбцу единичной матрицы
        alpha = np.sqrt(np.dot(s,s)) # Эта и следующие 2 строки - формула (4) справа налево 
        kappa = 1 / np.sqrt(2 * np.dot(s, s - e * alpha))
        omega = (kappa * (s - alpha * e)).reshape(A.shape[0], 1)
        V = E - 2 * np.dot(omega, omega.T) # Формула (2)
        A = np.dot(V, A) # Домножаем матрицу системы на матрицу V, чтобы занулить k-ый столбец ниже главной диагонали
        b = np.dot(V, b) # Домножаем столбец неоднородности на матрицу V
        
    # Вычисление определителя
    det = 1
    for k in range(A.shape[0]):
        det *= A[k][k] # Произведение всех диагональных элементов получившейся треуголньой матрицы
    
    if len(b.shape) == 1:    # Если мы решаем систему Ax = b
        x = np.zeros(A.shape[0]) # Заводим нулевой вектор для будущего решения системы
        # Обратный ход метода Гаусса
        for i in range(A.shape[0]-1, -1, -1):
            summary = 0
            for j in range(i+1, A.shape[0]):
                summary += A[i][j]*x[j]
            x[i] = (b[i] - summary) / A[i][i]
        
        #Вычисление вектора невязки
        r = np.zeros(A.shape[0]) # Переменная для хранения значения вектора невязки
        for i in range(A.shape[0]):
            for j in range(A.shape[0]):
                r[i] += A[i][j]*x[j]; # r+=Ax
            r[i] -= b[i] #r-=b
        
        return x, r, det # Возвращаем значения решения, вектора невязки и определителя матрицы
    
    else: # Если решаем систему AX=E
        x = np.zeros((A.shape[0], A.shape[0])) # Заводим нулевую матрицу для хранения будущей обратной матрицы
        # Обратный ход метода Гаусса
        for i in range(A.shape[0]-1, -1, -1):
            summary = 0
            for j in range(i+1, A.shape[0]):
                summary += A[i][j]*x[i][j]
            for j in range(A.shape[0]):
                x[i][j] = (b[i][j] - summary) / A[i][i]
        
        return x # Возвращаем значение обратной матрицы

# Проверка результатов

1. При заданном $n$ сгенерировать случайным образом квадратную матрицу размера $n\times n$, имеющую диагональное доминирование. Элементы матрицы - действительные числа с двумя знаками после запятой.

In [3]:
from random import randint
 
n = int(input())
 
A = np.array([[randint(10, 1000) / 100 for _ in range(n)] for _ in range(n)]).astype(float)

summary = 0
for i in range(n):
    for j in range(n):
        if i != j:
            summary += math.fabs(A[i][j])
for i in range (n):
    if A[i][i] <= summary:
        A[i][i] = randint(int(summary)*100, 10000) / 100

print(*A, sep='\n')

 4


[77.9   5.46  8.44  9.89]
[ 1.31 83.86  1.13  8.06]
[ 9.11  2.09 74.52  6.02]
[ 2.53  8.39  2.33 80.92]


2. Сгенерировать случайным образом вектор решений $x$ (два знака после запятой).

In [4]:
x = np.array([randint(10, 1000) / 100 for _ in range(n)]).astype(float)

print(*x, sep='\n')

0.41
1.03
8.76
9.24


3. По сгенерированным данным вычислить вектор $b$ свободных членов системы по формуле $b = Ax$.

In [5]:
b = A.dot(x)

print(*b, sep='\n')

202.88080000000002
171.2861
714.3077999999999
777.7906


4. Для полученных данных:

    a) найти решение системы указанным методом.

In [6]:
_x, r, det = reflection_method(A, b)

print(*_x, sep='\n')

0.4099999999999993
1.03
8.760000000000002
9.24


Выполнить проверку путем вычисления вектора невязки.

In [7]:
print(*r)

0.0 0.0 -1.1368683772161603e-13 1.1368683772161603e-13


б) найти матрицу, обратную к матрице системы.

In [8]:
A_inv = reflection_method(A, np.eye(n))
print(*A_inv, sep='\n')

[0.01264709 0.00021268 0.00147901 0.00041075]
[-0.00025664  0.01182182  0.0001749   0.00115111]
[-0.00159488 -0.00026422  0.01359472  0.00029227]
[-0.00034781 -0.00122434 -0.00033435  0.01254722]


Выполнить проверку;

In [9]:
E = np.dot(A_inv, A)

for i in range(n):
    for j in range(n):
        E[i,j] = round(np.absolute(E[i,j]), 0) # Преобразуем "единичниую" матрицу, округлив до двух знаков после запятой
        
print(*E, sep='\n')

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


в) вычислить определитель матрицы системы;

In [10]:
print(det)

-38234039.47928281


г) найти число обусловленности.

In [11]:
nu = np.linalg.norm(A, 2) * np.linalg.norm(A_inv, 2)
print(nu)

1.319080323545186
